CREATE TABLE IF NOT EXISTS ballotMeasures(
  id SERIAL PRIMARY KEY,
  measureText VARCHAR(1000) NOT NULL,
  measureOptions VARCHAR(60)[] NOT NULL
);

CREATE TABLE IF NOT EXISTS voterAddress(
  id SERIAL PRIMARY KEY,
  line1 VARCHAR(100) NOT NULL,
  line2 VARCHAR(100),
  zipcode VARCHAR(5) NOT NULL,
  city VARCHAR(30) NOT NULL,
  state VARCHAR(2) NOT NULL
);

CREATE TABLE IF NOT EXISTS voterRegistration(
  id SERIAL PRIMARY KEY,
  firstName VARCHAR(30) NOT NULL,
  middleName VARCHAR(30),
  lastName VARCHAR(30) NOT NULL,
  ssn VARCHAR(60) NOT NULL,
  addressId SERIAL NOT NULL,
  dob DATE NOT NULL,
  FOREIGN KEY(addressId)
    REFERENCES voterAddress(id)
);